Test: Test.c All.h All.c
	gcc -Wall -pedantic Test.c All.h All.c -o end -fprofile-arcs -ftest-coverage
Test1: Test1.c All.h All.c
	gcc -Wall -pedantic Test1.c All.h All.c -o test1 -fprofile-arcs -ftest-coverage
Test2: Test2.c All.h All.c
	gcc -Wall -pedantic Test2.c All.h All.c -o test2

