Lab2.2.6: Lab2.2.6.c Lab2.2.6.h
	gcc -ansi -pedantic lab2.2.6.c -o lab2.2.6 -lm
Lab2.2.6Test: Lab2.2.6.c Lab2.2.6.h Lab2.2.6Test.c
	gcc -ansi -pedantic Lab2.2.6Test.c Lab2.2.6.c -o Lab2.2.6Test -lm -D TESTING 
