name: Builder

on:
  push:
    paths:
     - 'Lab7Test/**'
    

jobs:
  build:


    runs-on: windows-latest
    steps:   
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Testing
      run: |
            cd Lab7Test
            make Lab7Test
            ./end 
    - name: Codecovfirst
      run:  curl -s https://codecov.io/bash | bash -s - -t token
