name: Builder

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
           make test
           cd Lab1/Lab1
    - run: |
           cd Lab1/Lab1 
           ./Lab1_Test
