name: Builder

on:
  push:
    paths:
     - 'Lab6/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
            cd Lab6
            make Lab6Test
            ./Lab6Test
