name: Builder

on:
  push:
    paths:
     - 'Lab3/**'
    

jobs:
  build:


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
            cd Lab3
            make TestAll
