name: Builder

on:
  push:
    paths:
     - 'Lab7Test/**'
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Albums
      run: | 
            cd Lab7
            make Test
            ./end
