name: Builder

on:
  push:
    paths:
     - 'Lab7Test/**'
    

jobs:
  build:


    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Testing
      run: |
            make TestAll -ะก Lab7Test
