name: Builder

on:
  push:
    paths:
     - 'Lab7Test/**'
    

jobs:
  build:


    runs-on: windows-latest
    steps:   
    - name: Install codecov
      run: choco install codecov
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Testing
      run: |
            cd Lab7Test
            make Test1
            ./test1 
            
    - name: Codecov
      run: codecov -f "test1" -t CODECOV_TOKEN="d15c1448-8d9f-459c-a36b-7c9d789c1f13" 
