name: Builder

on:
  push:
    paths:
     - 'Lab7/**'
    

jobs:
  build:


    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Perfomances
      run: | 
            cd Lab7
            make Perfomances
            ./perfoTest
