name: Builder

on:
  push:
    paths:
     - 'Lab7/**'
    

jobs:
  build:


    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: GenresTest
      run: |
            cd Lab7
            make Genres
            ./gen
    - name: Perfomances
      run: | 
            cd Lab7
            make Perfomances
            ./perfoTest
    - name: Albums
      run: |
            cd Lab7
            make Albums
            ./albumsTest
    - name: UI
      run: | 
            cd Lab7
            make UI
            ./uiTest
