name: Builder

on:
  push:
    branches: [ main ]

jobs:
  build:


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
            cd Lab1
            make Lab1_Test
    - run: |
           cd Lab1 
           ./Lab1_Test
