name: build-and-test

on: 
  push:
      paths: 
      - 'Lab2/Lab2.13/**'

jobs:

  BuildAndTest:

    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Valgring
      run: |
          sudo apt install valgrind
          
    - name: Test them all
      run: make TESTALL -C Lab2/Lab2.13
