name: build-and-test

on: 
  push:
    paths:
    - 'Lab5/**'

jobs:

  BuildAndTest:

    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Valgring
      run: |
          sudo apt install valgrind
          
    - name: Testing
      run: make TestAll -C Lab5
