Genres:
	gcc Genres.h Genres.c main.h main.c -o test -D=TESTING
	./test
Perfomances:
	gcc Perfomances.h Perfomances.c -o perf 
	./perf
Albums:
	gcc -pedantic Albums.c Albums.h main.c main.h -o albumsTest
	./albumsTest
UI:
	gcc -pedantic UI.c UI.h main.c main.h Albums.c Albums.h Genres.c Genres.h Perfomances.c Perfomances.h -o uiTest
	./uiTest
thend:
	gcc -pedantic Test.c Test.h UI.c UI.h main.c main.h Albums.c Albums.h Genres.c Genres.h Perfomances.c Perfomances.h -o thEND -D=TESTING
	./thEND
	
